# Generated by Django 4.2.6 on 2023-10-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_Create_store_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
