# Generated by Django 4.2.6 on 2023-10-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_adress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
