# Generated by Django 4.2.6 on 2024-06-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send_private_email', 'Can send private email to user by the button')]},
        ),
    ]
